//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumsDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public string title { get; set; }
        public string content { get; set; }
        public string forumName { get; set; }
        public string subForumName { get; set; }
        public string userName { get; set; }
        public System.DateTime creation { get; set; }
        public int serialNumber { get; set; }
        public int parentPost { get; set; }
    }
}
